# Generated by Django 5.2.3 on 2025-07-08 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotball', '0002_rename_group_rolegroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='fotball.child', verbose_name='Имя ребенка'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(verbose_name='Дата посещения тренировки'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='fotball.rolegroup', verbose_name='Группа занимающегося'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина отсутсвия'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.BooleanField(verbose_name='Был\\Не был'),
        ),
        migrations.AlterField(
            model_name='child',
            name='birth_date',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='child',
            name='full_name',
            field=models.CharField(max_length=250, verbose_name='ФИО ребенка'),
        ),
        migrations.AlterField(
            model_name='child',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='fotball.rolegroup', verbose_name='Группа ребенка'),
        ),
        migrations.AlterField(
            model_name='child',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Посещает тренировки Да\\Нет'),
        ),
        migrations.AlterField(
            model_name='child',
            name='parent_name',
            field=models.CharField(max_length=250, verbose_name='Имя родителя'),
        ),
        migrations.AlterField(
            model_name='child',
            name='phone_number',
            field=models.CharField(max_length=12, verbose_name='Номер телефона родителя'),
        ),
        migrations.AlterField(
            model_name='rolegroup',
            name='age_level',
            field=models.CharField(choices=[('S', 'Младшая'), ('M', 'Средняя'), ('L', 'Старшая')], max_length=1, verbose_name='Возрастная группа'),
        ),
        migrations.AlterField(
            model_name='rolegroup',
            name='kindergarten_number',
            field=models.CharField(max_length=20, verbose_name='Номер сада'),
        ),
        migrations.AlterField(
            model_name='rolegroup',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название группы'),
        ),
        migrations.AlterField(
            model_name='rolegroup',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='fotball.trainer', verbose_name='Тренер в групе'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Контактный телефон'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_profile', to='fotball.user', verbose_name='Учетная запись'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='Пароль пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('trainer', 'Тренер'), ('parent', 'Родитель')], max_length=10, verbose_name='Роль пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='Логин пользователя'),
        ),
        migrations.CreateModel(
            name='TrainingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Стоимость одного занятия')),
                ('active_form', models.DateField(verbose_name='Дата начала действия цены')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_rates', to='fotball.rolegroup', verbose_name='Группа')),
            ],
        ),
    ]
