# Generated by Django 5.2.3 on 2025-07-08 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fotball', '0003_alter_attendance_child_alter_attendance_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoleGroup',
            new_name='GroupKidGarden',
        ),
    ]
