# Generated by Django 5.2.3 on 2025-07-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotball', '0004_rename_rolegroup_groupkidgarden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='user',
        ),
        migrations.AddField(
            model_name='trainer',
            name='work_space',
            field=models.CharField(default=1, max_length=500, verbose_name='Номер сада и группы где ведет заниятие данный тренер'),
            preserve_default=False,
        ),
    ]
