# Generated by Django 5.2.3 on 2025-07-27 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotball', '0005_remove_trainer_user_trainer_work_space'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='work_space',
        ),
        migrations.AddField(
            model_name='trainer',
            name='kindergarten',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trainers', to='fotball.groupkidgarden', verbose_name='Детский сад'),
            preserve_default=False,
        ),
    ]
