# Generated by Django 5.2.3 on 2025-07-27 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotball', '0006_remove_trainer_work_space_trainer_kindergarten'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='kindergarten',
        ),
        migrations.AddField(
            model_name='trainer',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='trainers', to='fotball.groupkidgarden', verbose_name='Группы'),
        ),
        migrations.AlterField(
            model_name='groupkidgarden',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_groups', to='fotball.trainer', verbose_name='Тренер в групе'),
        ),
    ]
