# Generated by Django 5.2.3 on 2025-08-01 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotball', '0007_remove_trainer_kindergarten_trainer_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='work_space',
            field=models.CharField(default=1, max_length=500, verbose_name='Номер сада и группы где ведет заниятие данный тренер'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='child',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_group', to='fotball.groupkidgarden', verbose_name='Группа ребенка'),
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250, verbose_name='ФИО родителя')),
                ('phone', models.CharField(max_length=20, verbose_name='Контактный телефон')),
                ('children', models.ManyToManyField(blank=True, related_name='parents', to='fotball.child', verbose_name='Дети')),
            ],
        ),
        migrations.AddField(
            model_name='child',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_parent', to='fotball.parent', verbose_name='Родитель'),
        ),
    ]
