# Generated by Django 5.2.3 on 2025-08-01 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotball', '0008_trainer_work_space_alter_child_group_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='child',
            name='parent_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_parent', to='fotball.parent', verbose_name='Имя родителя'),
        ),
    ]
