# Generated by Django 5.2.3 on 2025-08-01 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fotball', '0009_remove_child_phone_number_alter_child_parent_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='parent',
        ),
    ]
