# Generated by Django 5.2.3 on 2025-08-01 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fotball', '0010_remove_child_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='linked_child',
        ),
        migrations.RemoveField(
            model_name='user',
            name='linked_trainer',
        ),
    ]
