# Generated by Django 5.2.3 on 2025-08-01 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotball', '0011_remove_user_linked_child_remove_user_linked_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='linked_child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_linked', to='fotball.child'),
        ),
        migrations.AddField(
            model_name='user',
            name='linked_trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_linked', to='fotball.trainer'),
        ),
    ]
