# Generated by Django 5.2.3 on 2025-09-06 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotball', '0012_user_linked_child_user_linked_trainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_file', models.FileField(upload_to='medical_certificates/%Y/%m/%d/', verbose_name='Файл справки')),
                ('date_from', models.DateField(verbose_name='Дата начала болезни')),
                ('date_to', models.DateField(verbose_name='Дата окончания болезни')),
                ('description', models.TextField(help_text='Краткое описание заболевания', verbose_name='Описание болезни')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрена'), ('rejected', 'Отклонена')], default='pending', max_length=10, verbose_name='Статус')),
                ('admin_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий администратора')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_certificates', to='fotball.child', verbose_name='Ребенок')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_certificates', to='fotball.user', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Справка о болезни',
                'verbose_name_plural': 'Справки о болезнях',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
