# Generated by Django 5.2.3 on 2025-09-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotball', '0013_medicalcertificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalcertificate',
            name='description',
        ),
        migrations.AddField(
            model_name='medicalcertificate',
            name='absence_reason',
            field=models.TextField(default='', help_text='Описание причины отсутствия для перерасчета', verbose_name='Причина отсутствия'),
        ),
        migrations.AddField(
            model_name='medicalcertificate',
            name='cost_per_lesson',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=8, verbose_name='Стоимость одного занятия'),
        ),
        migrations.AddField(
            model_name='medicalcertificate',
            name='note',
            field=models.TextField(blank=True, default='', help_text='Дополнительная информация', verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='medicalcertificate',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Общая стоимость к оплате'),
        ),
    ]
