# Generated by Django 5.2.3 on 2025-09-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotball', '0014_remove_medicalcertificate_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalcertificate',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='medical_certificates/%Y/%m/%d/', verbose_name='Файл справки'),
        ),
    ]
