# Generated by Django 5.2.3 on 2025-09-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotball', '0015_alter_medicalcertificate_certificate_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalcertificate',
            name='cost_per_lesson',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10, verbose_name='Стоимость одного занятия'),
        ),
        migrations.AlterField(
            model_name='medicalcertificate',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Общая стоимость к оплате'),
        ),
    ]
