# Generated by Django 5.2.3 on 2025-09-07 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotball', '0016_alter_medicalcertificate_cost_per_lesson_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата тренировки')),
                ('time', models.TimeField(verbose_name='Время тренировки')),
                ('duration_minutes', models.PositiveIntegerField(default=40, verbose_name='Продолжительность (минуты)')),
                ('location', models.CharField(blank=True, default='', max_length=200, verbose_name='Место проведения')),
                ('status', models.CharField(choices=[('scheduled', 'Запланирована'), ('completed', 'Проведена'), ('cancelled', 'Отменена')], default='scheduled', max_length=10, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_trainings', to='fotball.user', verbose_name='Создано администратором')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_trainings', to='fotball.groupkidgarden', verbose_name='Группа')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_trainings', to='fotball.trainer', verbose_name='Тренер')),
            ],
            options={
                'verbose_name': 'Тренировка',
                'verbose_name_plural': 'Расписание тренировок',
                'ordering': ['date', 'time'],
                'unique_together': {('group', 'date', 'time')},
            },
        ),
    ]
