# Generated by Django 5.2.3 on 2025-09-07 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fotball', '0017_trainingschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupkidgarden',
            name='trainer',
        ),
    ]
