# Generated by Django 5.2.3 on 2025-09-07 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotball', '0018_remove_groupkidgarden_trainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_comments', to='fotball.child', verbose_name='Ребенок')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='fotball.trainer', verbose_name='Тренер')),
            ],
            options={
                'verbose_name': 'Комментарий тренера',
                'verbose_name_plural': 'Комментарии тренеров',
                'ordering': ['-created_at'],
            },
        ),
    ]
