# Generated by Django 5.2.3 on 2025-09-13 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotball', '0019_trainercomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleChangeNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('date_changed', 'Изменена дата'), ('time_changed', 'Изменено время'), ('both_changed', 'Изменены дата и время'), ('cancelled', 'Тренировка отменена')], max_length=20, verbose_name='Тип изменения')),
                ('old_date', models.DateField(blank=True, null=True, verbose_name='Старая дата')),
                ('new_date', models.DateField(blank=True, null=True, verbose_name='Новая дата')),
                ('old_time', models.TimeField(blank=True, null=True, verbose_name='Старое время')),
                ('new_time', models.TimeField(blank=True, null=True, verbose_name='Новое время')),
                ('message', models.TextField(verbose_name='Сообщение для пользователей')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_read_by_trainer', models.BooleanField(default=False, verbose_name='Прочитано тренером')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_notifications', to='fotball.user', verbose_name='Создано администратором')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_notifications', to='fotball.trainingschedule', verbose_name='Тренировка')),
            ],
            options={
                'verbose_name': 'Уведомление об изменении расписания',
                'verbose_name_plural': 'Уведомления об изменениях расписания',
                'ordering': ['-created_at'],
            },
        ),
    ]
