# Generated by Django 5.2.3 on 2025-09-13 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotball', '0020_schedulechangenotification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedulechangenotification',
            options={},
        ),
        migrations.CreateModel(
            name='NotificationRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True, verbose_name='Время прочтения')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fotball.schedulechangenotification', verbose_name='Уведомление')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fotball.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Прочитанное уведомление',
                'verbose_name_plural': 'Прочитанные уведомления',
                'ordering': ['-read_at'],
                'unique_together': {('user', 'notification')},
            },
        ),
    ]
