# Generated by Django 5.2.3 on 2025-09-20 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotball', '0021_alter_schedulechangenotification_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_month', models.DateField(verbose_name='Месяц счета')),
                ('total_trainings', models.PositiveIntegerField(verbose_name='Общее количество тренировок')),
                ('confirmed_absences', models.PositiveIntegerField(default=0, verbose_name='Подтвержденные пропуски по болезни')),
                ('billable_trainings', models.PositiveIntegerField(verbose_name='Тренировки к оплате')),
                ('price_per_training', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость одной тренировки')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая сумма к оплате')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачено'), ('overdue', 'Просрочено'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус оплаты')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата выставления')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты')),
                ('due_date', models.DateField(verbose_name='Срок оплаты')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fotball.child', verbose_name='Ребенок')),
            ],
            options={
                'verbose_name': 'Счет на оплату',
                'verbose_name_plural': 'Счета на оплату',
                'ordering': ['-invoice_month', 'child__full_name'],
                'unique_together': {('child', 'invoice_month')},
            },
        ),
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_training', models.DecimalField(decimal_places=2, default=500.0, max_digits=10, verbose_name='Стоимость одной тренировки')),
                ('default_trainings_per_month', models.PositiveIntegerField(default=8, verbose_name='Количество тренировок по умолчанию в месяц')),
                ('invoice_generation_day', models.PositiveIntegerField(default=25, verbose_name='День месяца для выставления счетов')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('kindergarten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fotball.groupkidgarden', verbose_name='Детский сад')),
            ],
            options={
                'verbose_name': 'Настройки оплаты',
                'verbose_name_plural': 'Настройки оплаты',
                'unique_together': {('kindergarten',)},
            },
        ),
    ]
