# Generated by Django 4.2.27 on 2026-02-08 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fotball', '0022_paymentinvoice_paymentsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedulechangenotification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Уведомление об изменении расписания', 'verbose_name_plural': 'Уведомления об изменениях расписания'},
        ),
        migrations.CreateModel(
            name='TrainingCancellationNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancelled_date', models.DateField(verbose_name='Дата отмененной тренировки')),
                ('cancelled_time', models.TimeField(verbose_name='Время отмененной тренировки')),
                ('reason', models.TextField(verbose_name='Причина отмены')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_read_by_trainer', models.BooleanField(default=False, verbose_name='Прочитано тренером')),
                ('is_read_by_parents', models.BooleanField(default=False, verbose_name='Прочитано родителями')),
                ('affects_payment', models.BooleanField(default=True, verbose_name='Влияет на оплату')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fotball.user', verbose_name='Кто отменил')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fotball.groupkidgarden', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Уведомление об отмене тренировки',
                'verbose_name_plural': 'Уведомления об отмене тренировок',
                'ordering': ['-created_at'],
            },
        ),
    ]
