# Generated by Django 4.2.27 on 2026-02-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotball', '0026_paymentreceipt_parsed_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalPaymentQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='payment_qr_global/', verbose_name='QR-код для оплаты')),
            ],
            options={
                'verbose_name': 'Общий QR для оплаты',
                'verbose_name_plural': 'Общий QR для оплаты',
            },
        ),
    ]
