# Generated by Django 4.2.27 on 2026-02-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotball', '0027_global_payment_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последний вход'),
        ),
    ]
